/**
 * Voice-over line banks — Gen Z style, kocak, sopan.
 * Each condition has 15-30 variants to avoid monotony.
 * Sorted by condition: normal, streak, comeback, bigLead, closeFight, taunt, deuce.
 */

// ── NORMAL POINT (team just scored, no special condition) ──
export const normalPoint = {
  id: [
    (s, o) => `Poin untuk ${s}! Mantap jiwa!`,
    (s, o) => `${s} dapat poin! Oke gas terus!`,
    (s, o) => `Masuk! Poin buat ${s}! Sip lah!`,
    (s, o) => `Nice one ${s}! Lanjutkan!`,
    (s, o) => `${s} nambah poin! Keep going!`,
    (s, o) => `Yess ${s}! Masuk tuh!`,
    (s, o) => `Poin ${s}! Enak banget mainnya!`,
    (s, o) => `Oke ${s} berhasil nambah poin!`,
    (s, o) => `${s} gak mau kalah nih! Masuk lagi!`,
    (s, o) => `Satu poin buat ${s}! Semangat!`,
    (s, o) => `Poin! ${s} makin pede nih!`,
    (s, o) => `${s} cuan satu poin! Gaskeun!`,
    (s, o) => `Wih ${s} masuk! Keren!`,
    (s, o) => `${s} nambah koleksi poin! Ayo!`,
    (s, o) => `Poin buat ${s}! ${o} harus hati hati nih!`,
    (s, o) => `${s} eksekusi dengan sempurna! Masuk!`,
    (s, o) => `${s} oke punya! Satu poin lagi!`,
    (s, o) => `Masuk bro! ${s} tambahin skornya!`,
    (s, o) => `Kena! Poin ${s}! ${o} sabar ya!`,
    (s, o) => `${s} gak main main nih! Poin masuk!`,
  ],
  en: [
    (s, o) => `Point for ${s}! Nice one!`,
    (s, o) => `${s} scores! Let's go!`,
    (s, o) => `Great shot by ${s}! Point!`,
    (s, o) => `${s} adds another one! Keep it up!`,
    (s, o) => `That's a point for ${s}! Well played!`,
    (s, o) => `${s} with a clean point! Amazing!`,
    (s, o) => `Point ${s}! Looking strong!`,
    (s, o) => `Yes! ${s} takes the point!`,
    (s, o) => `Beautiful play by ${s}! One more point!`,
    (s, o) => `${s} is looking sharp! Point!`,
    (s, o) => `Another point for ${s}! ${o} needs to respond!`,
    (s, o) => `${s} with a solid execution! Point!`,
    (s, o) => `That's how it's done! Point for ${s}!`,
    (s, o) => `Boom! ${s} gets the point!`,
    (s, o) => `${s} is heating up! Point scored!`,
  ],
};

// ── STREAK (3+ consecutive points by same team) ──
export const streakPoint = {
  id: [
    (s, o) => `Anjay masuk lagi ${s}! Gak bisa dihentikan!`,
    (s, o) => `${s} lagi on fire broo! Masuk lagii!`,
    (s, o) => `Gilaa ${s} berturut turut! ${o} ketar ketir nih!`,
    (s, o) => `Lagi lagi ${s}! ${o} mana nih suaranya?`,
    (s, o) => `${s} mana suaranya! Masuk terus nih!`,
    (s, o) => `Suporter ${s} sorakin dong tim kalian! Masuk mulu!`,
    (s, o) => `${s} gak kasih ampun! ${o} harus bangun nih!`,
    (s, o) => `Serius ${s} menggila! ${o} kok diem aja!`,
    (s, o) => `Hatrick poin! ${s} lagi mode beast!`,
    (s, o) => `${s} kayak lagi cheat! Masuk mulu bro!`,
    (s, o) => `Rally ${s}! ${o} sabar ya nanti giliran kalian!`,
    (s, o) => `${s} sedang dalam momentum terbaiknya!`,
    (s, o) => `Yaa ampun ${s} gak mau berhenti! Keren parah!`,
    (s, o) => `${s} lagi gak bisa di stop! ${o} cari cara dong!`,
    (s, o) => `Brutal! ${s} ngegas terus! Berturut turut!`,
    (s, o) => `${o} harus timeout nih! ${s} gak ada obat!`,
    (s, o) => `Main apa sih ${s}? Bagus banget gak ngerti!`,
    (s, o) => `Wah ${s} lagi di zona! Semua masuk!`,
    (s, o) => `${s} bikin ${o} pusing! Masuk lagi aja!`,
    (s, o) => `Sumpah ${s} ngeri banget mainnya! Lagi lagi masuk!`,
  ],
  en: [
    (s, o) => `${s} is on fire! Another one!`,
    (s, o) => `Unstoppable! ${s} keeps scoring!`,
    (s, o) => `What a streak by ${s}! ${o} can't handle this!`,
    (s, o) => `${s} is absolutely dominating! ${o} needs help!`,
    (s, o) => `Again! ${s} with another point! Incredible!`,
    (s, o) => `${s} fans, make some noise! Your team is flying!`,
    (s, o) => `${s} is in beast mode! ${o} has no answer!`,
    (s, o) => `Three in a row! ${s} is unstoppable!`,
    (s, o) => `${s} won't stop scoring! This is insane!`,
    (s, o) => `${o} better wake up! ${s} is running away with this!`,
    (s, o) => `The crowd goes wild! ${s} is on a roll!`,
    (s, o) => `${s} is playing out of their mind! What a streak!`,
    (s, o) => `Hold on ${o}! ${s} is not slowing down!`,
    (s, o) => `${s} is in the zone! Everything is going in!`,
    (s, o) => `Incredible rally by ${s}! ${o} looks stunned!`,
  ],
};

// ── COMEBACK (team was behind, now tied or took the lead) ──
export const comebackPoint = {
  id: [
    (s, o) => `Wah ${s} bangkit! Jangan ditinggal tidur ${o}!`,
    (s, o) => `Cie ${s} mulai nyusul nih! ${o} awas ya!`,
    (s, o) => `${s} gak mau kalah! Mulai ngejar nih!`,
    (s, o) => `Comeback is real! ${s} mulai bangkit!`,
    (s, o) => `${o} jangan senang dulu! ${s} udah mulai panas!`,
    (s, o) => `${s} bilang belum selesai! Masih panjang pertandingannya!`,
    (s, o) => `Jangan remehkan ${s}! Mereka bangkit sekarang!`,
    (s, o) => `${s} mulai nunjukin taringnya! ${o} harus waspada!`,
    (s, o) => `Plot twist nih! ${s} ngejar ${o}!`,
    (s, o) => `${s} gak terima tertinggal! Ayo kejar!`,
    (s, o) => `Ini dia comeback yang ditunggu tunggu! ${s} mulai gaspol!`,
    (s, o) => `${s} kayak anime! Kalah dulu baru menang! Ayo!`,
    (s, o) => `${o} keunggulannya mulai menipis! ${s} ngejar nih!`,
    (s, o) => `Never give up! ${s} buktiin mereka bisa bangkit!`,
    (s, o) => `Aduh ${o} kok kasih ${s} comeback! Awas lo!`,
    (s, o) => `Wih ${s} main character moment nih!`,
    (s, o) => `${s} mode comeback activated! Gak bisa diremehkan!`,
    (s, o) => `${o} mulai grogi nih kayaknya! ${s} ngejar!`,
    (s, o) => `Sabar ${o}! ${s} lagi dalam mode pantang menyerah!`,
    (s, o) => `${s} buktiin mental juara! Bangkit dari ketinggalan!`,
  ],
  en: [
    (s, o) => `What a comeback by ${s}! ${o}, watch out!`,
    (s, o) => `${s} is fighting back! This is getting exciting!`,
    (s, o) => `Don't count ${s} out! They're coming back!`,
    (s, o) => `${o} better stay focused! ${s} is catching up!`,
    (s, o) => `The comeback is real! ${s} is closing the gap!`,
    (s, o) => `${s} says not so fast! Still in this game!`,
    (s, o) => `Plot twist! ${s} is making a run for it!`,
    (s, o) => `${o}'s lead is shrinking! ${s} is on the move!`,
    (s, o) => `Never underestimate ${s}! They're back in it!`,
    (s, o) => `This is the comeback everyone was waiting for!`,
    (s, o) => `${s} with a main character moment! Fighting back!`,
    (s, o) => `Hold on tight! ${s} is closing in on ${o}!`,
    (s, o) => `${s} refuses to give up! What a spirit!`,
    (s, o) => `${o} getting nervous! ${s} is right behind them!`,
    (s, o) => `${s} proving their champion mentality! What a comeback!`,
  ],
};

// ── BIG LEAD (5+ point advantage) ──
export const bigLeadPoint = {
  id: [
    (s, o) => `${s} makin jauh aja! ${o} harus kerja keras nih!`,
    (s, o) => `Jauh banget ${s} unggulnya! ${o} ayo dong!`,
    (s, o) => `${s} udah santai nih kayaknya! Jauh banget!`,
    (s, o) => `Aduh ${o} tertinggal jauh! ${s} mendominasi!`,
    (s, o) => `Gap nya makin lebar! ${s} lagi dominant mode!`,
    (s, o) => `${s} cruise control! ${o} butuh keajaiban nih!`,
    (s, o) => `Waduh ${o} jauh banget ketinggalannya! Ayo bangkit!`,
    (s, o) => `${s} gak kasih celah! Dominan banget!`,
    (s, o) => `${o} butuh comeback gede nih! ${s} udah jauh!`,
    (s, o) => `Suporter ${o} tetap semangat ya! Masih ada peluang!`,
    (s, o) => `${s} main kayak lagi latihan! Mulus banget!`,
    (s, o) => `Oke ini ${s} bener bener nge bossin ${o}!`,
    (s, o) => `${o} harus punya strategi baru nih, udah jauh!`,
    (s, o) => `${s} udah kayak main sama bot! Gampang banget!`,
    (s, o) => `Skornya makin jauh! ${s} mendominasi pertandingan!`,
  ],
  en: [
    (s, o) => `${s} is pulling away! ${o} needs a miracle!`,
    (s, o) => `Huge lead for ${s}! ${o} has to step up now!`,
    (s, o) => `${s} is dominating this game! What a performance!`,
    (s, o) => `The gap keeps growing! ${s} is in total control!`,
    (s, o) => `${o} needs a big comeback! ${s} is way ahead!`,
    (s, o) => `${s} is making this look easy! Dominant display!`,
    (s, o) => `${o} fans, keep cheering! Your team needs you now!`,
    (s, o) => `${s} is cruising! What a commanding lead!`,
    (s, o) => `This is a masterclass by ${s}! ${o} can't keep up!`,
    (s, o) => `${s} is in a league of their own right now!`,
  ],
};

// ── CLOSE FIGHT (score within 2 points, both above 10) ──
export const closeFightPoint = {
  id: [
    (s, o) => `Ketat banget! ${s} unggul tipis!`,
    (s, o) => `Seru nih pertandingannya! ${s} masih unggul!`,
    (s, o) => `Gak ada yang mau ngalah! ${s} nambah satu!`,
    (s, o) => `Deg degan! ${s} selangkah di depan!`,
    (s, o) => `Pertandingan super ketat! Poin buat ${s}!`,
    (s, o) => `Siapa yang bakal menang? ${s} sementara unggul!`,
    (s, o) => `Penontonnya pada tegang nih! ${s} masih leading!`,
    (s, o) => `${s} nambah tapi ${o} pasti gak mau kalah!`,
    (s, o) => `Wuih intense banget! ${s} masih di atas!`,
    (s, o) => `Pertarungan seru! ${s} belum mau lepas keunggulan!`,
    (s, o) => `Tipis banget! ${s} harus jaga fokus!`,
    (s, o) => `Nail biter! ${s} sementara memimpin! Seru!`,
    (s, o) => `Gak bisa kedip! ${s} nambah poin lagi!`,
    (s, o) => `Match of the day nih! ${s} masih unggul tipis!`,
    (s, o) => `${o} jangan sampai lengah! ${s} terus ngejar!`,
  ],
  en: [
    (s, o) => `So close! ${s} takes a slim lead!`,
    (s, o) => `What a match! ${s} edges ahead!`,
    (s, o) => `Neither team is giving up! Point for ${s}!`,
    (s, o) => `This is intense! ${s} stays in front!`,
    (s, o) => `Edge of your seat stuff! ${s} with the point!`,
    (s, o) => `Nail biter! ${s} holds the advantage!`,
    (s, o) => `Can't look away! ${s} adds to the lead!`,
    (s, o) => `${o} won't back down but ${s} keeps pushing!`,
    (s, o) => `What a battle! ${s} still in front!`,
    (s, o) => `The tension is real! Point for ${s}!`,
  ],
};

// ── TAUNT (directed at team that just got scored on) ──
export const tauntLines = {
  id: [
    (o) => `Ayo mana ${o} suaranya, semangatin timnya dong!`,
    (o) => `${o} kok diem aja sih, ayo semangat dong!`,
    (o) => `Mana nih suporter ${o}? Jangan mau kalah dong!`,
    (o) => `Ayo ${o} bangkit! Masa gitu doang!`,
    (o) => `${o} jangan nyerah! Masih bisa kok!`,
    (o) => `Suporter ${o} mana suaranya? Ayo semangatin!`,
    (o) => `${o} kayaknya butuh dukungan nih! Ayo teriak!`,
    (o) => `Gak apa apa ${o}, santai masih bisa ngejar!`,
    (o) => `${o} jangan down! Ini baru pemanasan!`,
    (o) => `Ayo dong ${o} jangan gitu! Masih ada peluang!`,
    (o) => `${o} lagi kurang hoki nih! Ayo semangat!`,
    (o) => `${o} harus lebih fokus nih! Jangan panik!`,
    (o) => `Tenang ${o}! Ini baru babak awal!`,
    (o) => `${o} perlu minum dulu kayaknya! Ayo fokus!`,
    (o) => `Suporter ${o} lebih keras dong! Tim kalian butuh semangat!`,
  ],
  en: [
    (o) => `Come on ${o} fans, where's the noise?`,
    (o) => `${o}, time to wake up! Let's go!`,
    (o) => `${o} supporters, your team needs you right now!`,
    (o) => `Don't be quiet ${o}! Cheer them on!`,
    (o) => `${o}, shake it off! You can do this!`,
    (o) => `${o} fans, make some noise! Rally your team!`,
    (o) => `${o} needs some energy from the crowd!`,
    (o) => `It's not over ${o}! Keep fighting!`,
    (o) => `${o}, don't give up! Still plenty of game left!`,
    (o) => `${o} looking for answers! Fans, support them!`,
  ],
};

// ── TIED GAME lines ──
export const tiedLines = {
  id: [
    (s) => `Imbang lagi! Seru banget pertandingan ini!`,
    (s) => `Balik lagi ke posisi sama! Siapa yang mau unggul?`,
    (s) => `Kejar kejaran! Skornya sama rata!`,
    (s) => `Gak ada yang mau ngalah! Imbang!`,
    (s) => `Wah seri lagi! Deg degan banget!`,
    (s) => `Poin ${s}! Sekarang imbang! Siapa yang mau duluan?`,
    (s) => `Gak bisa ditebak nih! Skor imbang lagi!`,
    (s) => `Reset! Kedua tim sekarang seimbang!`,
    (s) => `${s} menyamakan kedudukan! Panas nih!`,
    (s) => `Imbang bro! Ini pertandingan beneran seru!`,
  ],
  en: [
    (s) => `All tied up! What a match!`,
    (s) => `Back to level! Who wants it more?`,
    (s) => `${s} levels the score! This is exciting!`,
    (s) => `Neither team is backing down! Tied again!`,
    (s) => `Even steven! This game is on fire!`,
    (s) => `Reset! Both teams are level now!`,
    (s) => `${s} pulls it back to even! Intense!`,
    (s) => `Can't separate them! Score is level!`,
    (s) => `What a battle! Scores are tied!`,
    (s) => `Nobody is giving an inch! All square!`,
  ],
};

// ── BREAK / SET INTERVAL (looping voice-over during break) ──
export const breakLines = {
  id: [
    (tA, tB) => `Ayo suporter ${tA} mana suaranya! Lebih keras dong!`,
    (tA, tB) => `${tB} jangan kalah! Teriak yang kenceng!`,
    (tA, tB) => `Sementara break, ayo goyang dulu gaes!`,
    (tA, tB) => `Penonton yang di belakang mana suaranya!`,
    (tA, tB) => `Ayo semua joget bareng! Jangan malu malu!`,
    (tA, tB) => `Yang bawa makanan boleh makan dulu ya, nanti lanjut!`,
    (tA, tB) => `Suporter ${tA} pasti udah siapin yel yel kan? Ayo!`,
    (tA, tB) => `${tB} fans masa kalah rame sama ${tA}? Ayo dong!`,
    (tA, tB) => `Break sebentar! Minum dulu, goyang dulu!`,
    (tA, tB) => `Jangan lupa tetap semangat mendukung tim kalian ya!`,
    (tA, tB) => `Ayo yang belum teriak, ini saatnya! Siapa yang paling kenceng?`,
    (tA, tB) => `Setelah ini pertandingan makin seru! Siap siap ya gaes!`,
    (tA, tB) => `Buat yang baru dateng, selamat datang! Ayo ramaikan!`,
    (tA, tB) => `Penonton sebelah kiri mana suaranya! Sebelah kanan jangan kalah!`,
    (tA, tB) => `Ayo wave wave! Mulai dari kiri ke kanan!`,
  ],
  en: [
    (tA, tB) => `${tA} fans, let's hear you during the break!`,
    (tA, tB) => `${tB} supporters, don't be quiet! Make some noise!`,
    (tA, tB) => `Break time! Let's dance everybody!`,
    (tA, tB) => `Keep the energy up! The game continues soon!`,
    (tA, tB) => `Who's got the loudest fans? Let's find out!`,
    (tA, tB) => `Get your drinks, stretch your legs, and get ready!`,
    (tA, tB) => `The match continues after this break! Stay excited!`,
    (tA, tB) => `Left side of the crowd, make some noise! Right side, louder!`,
    (tA, tB) => `This is your chance to rest and recharge!`,
    (tA, tB) => `Grab a snack and get ready for more action!`,
  ],
};

// ── PANTUN KOCAK (during break) ──
export const breakPantun = {
  id: [
    "Ke pasar beli ketupat, pulangnya beli es dawet. Ayo penonton bersorak, biar pemain makin semangat!",
    "Burung kutilang hinggap di dahan, terbang ke barat kembali ke timur. Dukung tim jagoan, biar menangnya gak cuma di mimpi semata!",
    "Jalan jalan ke kota Sragen, pulangnya beli tape ketan. Ayo dong jangan cuma diem, teriak yang kenceng biar pemain senang!",
    "Beli rambutan di pinggir jalan, dapat bonus satu ikat. Main badminton emang keren, apalagi kalo penontonnya hebat!",
    "Naik motor pakai helm merah, jangan lupa bawa SIM. Ayo teriak sekeras kerasnya, biar lawan pada takut dan grogi!",
    "Pergi ke sawah cari belut, pulangnya mampir beli sate. Penonton semangat itu bagus, biar pemainnya mainnya lebih greget!",
    "Buah mangga jatuh ke got, anjing lewat kena getah. Ayo dong penonton yang di pojokan, jangan cuma nonton aja ikut teriak dong!",
    "Ke pasar beli tempe mendoan, enak dimakan sambil ngopi. Yang dukung ${tA} ayo teriak, yang dukung ${tB} jangan mau kalahhh!",
    "Terbang tinggi burung elang, hinggap di pohon jambu. Yuk kita semangatin bareng bareng, biar pertandingannya makin seru!",
    "Makan bakso pinggir jalan, kuahnya pedes bikin nagih. Pertandingannya juga seru, bikin penonton gak mau pulang!",
  ],
  en: [
    "Roses are red, violets are blue, cheer for your team, they need support from you!",
    "The crowd is alive, the energy is right, let's make this break, an unforgettable night!",
    "Clap your hands and stamp your feet, this badminton match just can't be beat!",
    "Left side loud, right side louder, let's see who's the prouder supporter!",
    "Take a breath and grab a drink, the next set is closer than you think!",
  ],
};

// ── PRESS PLAY WARNING ──
export const pressPlayLines = {
  id: [
    "Kak, tombol playnya pencet dulu dong kalo mau mulai! Kan saya gak tau, hehe.",
    "Eh sabar kak, pencet play dulu baru bisa main! Gak bisa langsung gitu dong!",
    "Belum dipencet play nya kak! Saya juga butuh persiapan dulu dong!",
    "Woi pencet play dulu dong! Masa langsung main aja, gak sopan banget!",
    "Halo kak, play dulu ya baru bisa nambah skor! Sabar sedikit!",
  ],
  en: [
    "Hey, press the play button first before adding points! I need to get ready!",
    "Hold on! Press play to start the set first!",
    "Can't add points yet! Hit that play button to begin!",
    "Easy there! Press play first, then we can score!",
    "The set hasn't started yet! Press play to continue!",
  ],
};
